version: '3'

services:
  buggybase2:
    build: ./buggybase2
    restart: always
    networks:
      default:
      internal:

  nginx:
    image: nginx:1.18
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 127.0.0.1:10090:80
    depends_on:
      - buggybase2

networks:
  default:
  internal:
    internal: true