version: '3'

services:
  sqli101:
    build: ./sqli101
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - FLAG=${FLAG}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      default:
      internal:

  nginx:
    image: nginx:1.18
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 127.0.0.1:10070:80
    depends_on:
      - sqli101

  db:
    image: mariadb:10.4.12
    restart: always
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Asia/Tokyo
    networks:
      internal:
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=30]

networks:
  default:
  internal:
    internal: true